version: '3.8'

services:
  spring-boot-app:
    image: pdt_sales_image:1.5
    container_name: pdt_sales-app-container
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ""

  postgres:
    image: postgres:13
    container_name: pdt_sales-postgres-container
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ""
    ports:
      - "5432:5432"
