version: '3.8'

services:
  pdt_sales-spring-boot-app:
    container_name: pdt_sales-spring-boot-app
    image: pdt_sales_image:v1.0.0
    build: .
    ports:
      - 8080:8080
    depends_on:
      - pdt_sales-postgres-db-container
    environment:
      - DATABASE_URL=jdbc:postgresql://pdt_sales-postgres-db-container:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres

  pdt_sales-postgres-db-container:
    image: postgres:13
    container_name: pdt_sales-postgres-db-container
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
