version: 2.1

orbs:
  docker: circleci/docker@2.4.0
  snyk: snyk/snyk@2.0.1
  maven: circleci/maven@1.4.1

executors:
  default-executor:
    docker:
      - image: cimg/openjdk:17.0.8

jobs:
  build: # Define the 'build' job
    executor: default-executor
    steps:
      - checkout  # Check out your code from version control
      
      # Add a step to update the permissions of the mvnw file
      - run:
          name: Update mvnw permissions
          command: chmod +x ./mvnw
      
      - run:
          name: Build Spring Boot App
          # Compile and package your Spring Boot app with Maven
          command: |
            ./mvnw clean package -DskipTests
            mv target/pdt_sales-0.0.1-SNAPSHOT.jar app.jar
      
  test:
    executor: default-executor
    steps:
      - checkout
      - run:
          name: Run 8 Spring Boot Unit Tests in 2 Java Files
          command: |
            mvn test 

  # synk_scan:
  #   executor: default-executor
  #   steps:
  #     - checkout
  #     - snyk/scan:
  #         name: Synk Security Scan
  #         organization: your-organization
  #         project: your-project-name

workflows:
  version: 2
  ci_flow:
    jobs:
      - build
      - test:
          requires:
            - build
      # - synk_scan:
      #     requires:
      #       - build
